<a href="https://colab.research.google.com/github/smoreira/TensorFlow2/blob/master/titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Imports
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, LabelEncoder

In [2]:
%tensorflow_version 2.x
import tensorflow as tf
print("You are using TensorFlow version", tf.__version__)
if len(tf.config.list_physical_devices('GPU')) > 0:
  print("You have a GPU enabled.")
else:
  print("Enable a GPU before running this notebook.")

You are using TensorFlow version 2.2.0-rc3
Enable a GPU before running this notebook.

### Upload Dataset Titanic Disaster

In [4]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving titanic_test.csv to titanic_test.csv
Saving titanic_train.csv to titanic_train.csv
User uploaded file "titanic_test.csv" with length 28629 bytes
User uploaded file "titanic_train.csv" with length 61194 bytes

In [0]:
train_data = pd.read_csv('titanic_train.csv')
test_data = pd.read_csv('titanic_test.csv')

In [0]:
train_data = train_data.join(pd.get_dummies(train_data['Sex']))
test_data = test_data.join(pd.get_dummies(test_data['Sex']))

In [0]:
train_data.loc[train_data['Embarked'].isnull(), 'Embarked'] = 'S'

In [0]:
embarked_encoder = LabelEncoder()
train_data['Embarked'] = embarked_encoder.fit_transform(train_data['Embarked'])
test_data['Embarked'] = embarked_encoder.transform(test_data['Embarked'])

In [0]:
train_data_male_age = train_data.loc[(train_data['Age'].notnull() & train_data['male'] == 1), 'Age']
test_data_male_age = test_data.loc[(test_data['Age'].notnull() & test_data['male'] == 1), 'Age']
male_avg_age = pd.concat([train_data_male_age, test_data_male_age]).mean()

train_data_female_age = train_data.loc[(train_data['Age'].notnull() & train_data['female'] == 1), 'Age']
test_data_female_age = test_data.loc[(test_data['Age'].notnull() & test_data['female'] == 1), 'Age']
female_avg_age = pd.concat([train_data_female_age, test_data_female_age]).mean()

train_data.loc[(train_data['Age'].isnull()) & (train_data['male'] == 1), 'Age'] = male_avg_age
test_data.loc[(test_data['Age'].isnull()) & (test_data['male'] == 1), 'Age'] = male_avg_age

train_data.loc[(train_data['Age'].isnull()) & (train_data['female'] == 1), 'Age'] = female_avg_age
test_data.loc[(test_data['Age'].isnull()) & (test_data['female'] == 1), 'Age'] = female_avg_age

In [0]:
test_data.loc[(test_data['Fare'].isnull())] = 14.5000

In [0]:
train_data.loc[(train_data['SibSp'] == 0) & (train_data['Parch'] == 0), 'Is_alone'] = 1
test_data.loc[(test_data['SibSp'] == 0) & (test_data['Parch'] == 0), 'Is_alone'] = 1

train_data.loc[(train_data['SibSp'] > 0) | (train_data['Parch'] > 0), 'Is_alone'] = 0
test_data.loc[(test_data['SibSp'] > 0) | (test_data['Parch'] > 0), 'Is_alone'] = 0

In [12]:
train_data.head()

   PassengerId  Survived  Pclass  ... female male  Is_alone
0            1         0       3  ...      0    1       0.0
1            2         1       1  ...      1    0       0.0
2            3         1       3  ...      1    0       1.0
3            4         1       1  ...      1    0       0.0
4            5         0       3  ...      0    1       1.0

[5 rows x 15 columns]

In [0]:
test_data_passenger_id = test_data['PassengerId']

columns_to_drop = ['PassengerId', 'Name', 'Ticket', 'Cabin', 'Sex', 'SibSp', 'Parch']
train_data.drop(columns=columns_to_drop, inplace=True)
train_data_columns = train_data.columns

test_data.drop(columns=columns_to_drop, inplace=True)
test_data_columns = test_data.columns

In [14]:
train_data.head()

   Survived  Pclass   Age     Fare  Embarked  female  male  Is_alone
0         0       3  22.0   7.2500         2       0     1       0.0
1         1       1  38.0  71.2833         0       1     0       0.0
2         1       3  26.0   7.9250         2       1     0       1.0
3         1       1  35.0  53.1000         2       1     0       0.0
4         0       3  35.0   8.0500         2       0     1       1.0

In [0]:
age_scaler = MinMaxScaler()
train_data['Age'] = age_scaler.fit_transform(train_data['Age'].values.reshape(-1, 1))
test_data['Age'] = age_scaler.transform(test_data['Age'].values.reshape(-1, 1))

fare_scaler = MinMaxScaler()
train_data['Fare'] = fare_scaler.fit_transform(train_data['Fare'].values.reshape(-1, 1))
test_data['Fare'] = fare_scaler.transform(test_data['Fare'].values.reshape(-1, 1))

train_data = pd.DataFrame(train_data)
train_data.columns = train_data_columns

test_data = pd.DataFrame(test_data)
test_data.columns = test_data_columns

In [0]:
train_data_label = train_data['Survived']
train_data.drop(columns=['Survived'], inplace=True)

In [17]:
train_data.head()

   Pclass       Age      Fare  Embarked  female  male  Is_alone
0       3  0.271174  0.014151         2       0     1       0.0
1       1  0.472229  0.139136         0       1     0       0.0
2       3  0.321438  0.015469         2       1     0       1.0
3       1  0.434531  0.103644         2       1     0       0.0
4       3  0.434531  0.015713         2       0     1       1.0

In [0]:
train_data = train_data.values
train_data_label = train_data_label.values

test_data = test_data.values

In [20]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(45, input_dim=7, activation='relu'))
model.add(tf.keras.layers.Dense(30, activation='relu'))
model.add(tf.keras.layers.Dense(20, activation='relu'))
model.add(tf.keras.layers.Dense(10, activation='relu'))

model.add(tf.keras.layers.Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(train_data, train_data_label, batch_size=100, epochs=150, verbose=1)

loss, accuracy = model.evaluate(train_data, train_data_label)
print(accuracy)

Epoch 1/150
9/9 [==============================] - 0s 2ms/step - loss: 0.6593 - accuracy: 0.6162
Epoch 2/150
9/9 [==============================] - 0s 2ms/step - loss: 0.6252 - accuracy: 0.6162
Epoch 3/150
9/9 [==============================] - 0s 2ms/step - loss: 0.5949 - accuracy: 0.6173
Epoch 4/150
9/9 [==============================] - 0s 2ms/step - loss: 0.5710 - accuracy: 0.6633
Epoch 5/150
9/9 [==============================] - 0s 2ms/step - loss: 0.5487 - accuracy: 0.7273
Epoch 6/150
9/9 [==============================] - 0s 2ms/step - loss: 0.5330 - accuracy: 0.7924
Epoch 7/150
9/9 [==============================] - 0s 2ms/step - loss: 0.5196 - accuracy: 0.7946
Epoch 8/150
9/9 [==============================] - 0s 2ms/step - loss: 0.5087 - accuracy: 0.8081
Epoch 9/150
9/9 [==============================] - 0s 2ms/step - loss: 0.5003 - accuracy: 0.7991
Epoch 10/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4887 - accuracy: 0.7969
Epoch 11/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4816 - accuracy: 0.7879
Epoch 12/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4728 - accuracy: 0.8070
Epoch 13/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4670 - accuracy: 0.7901
Epoch 14/150
9/9 [==============================] - 0s 1ms/step - loss: 0.4615 - accuracy: 0.7890
Epoch 15/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4559 - accuracy: 0.8058
Epoch 16/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4507 - accuracy: 0.8047
Epoch 17/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4460 - accuracy: 0.8070
Epoch 18/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4432 - accuracy: 0.8137
Epoch 19/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4401 - accuracy: 0.8126
Epoch 20/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4383 - accuracy: 0.8137
Epoch 21/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4386 - accuracy: 0.8114
Epoch 22/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4390 - accuracy: 0.8114
Epoch 23/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4396 - accuracy: 0.8025
Epoch 24/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4309 - accuracy: 0.8092
Epoch 25/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4327 - accuracy: 0.8126
Epoch 26/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4313 - accuracy: 0.8126
Epoch 27/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4293 - accuracy: 0.8114
Epoch 28/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4273 - accuracy: 0.8081
Epoch 29/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4280 - accuracy: 0.8092
Epoch 30/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4259 - accuracy: 0.8114
Epoch 31/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4252 - accuracy: 0.8092
Epoch 32/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4247 - accuracy: 0.8036
Epoch 33/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4256 - accuracy: 0.8092
Epoch 34/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4223 - accuracy: 0.8081
Epoch 35/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4221 - accuracy: 0.8103
Epoch 36/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4240 - accuracy: 0.8126
Epoch 37/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4227 - accuracy: 0.8103
Epoch 38/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4237 - accuracy: 0.8103
Epoch 39/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4214 - accuracy: 0.8148
Epoch 40/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4198 - accuracy: 0.8092
Epoch 41/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4186 - accuracy: 0.8092
Epoch 42/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4181 - accuracy: 0.8092
Epoch 43/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4199 - accuracy: 0.8081
Epoch 44/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4169 - accuracy: 0.8137
Epoch 45/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4191 - accuracy: 0.8171
Epoch 46/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4179 - accuracy: 0.8114
Epoch 47/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4167 - accuracy: 0.8137
Epoch 48/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4195 - accuracy: 0.8137
Epoch 49/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4173 - accuracy: 0.8193
Epoch 50/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4177 - accuracy: 0.8126
Epoch 51/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4194 - accuracy: 0.8215
Epoch 52/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4173 - accuracy: 0.8148
Epoch 53/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4143 - accuracy: 0.8227
Epoch 54/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4136 - accuracy: 0.8159
Epoch 55/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4159 - accuracy: 0.8137
Epoch 56/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4139 - accuracy: 0.8159
Epoch 57/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4122 - accuracy: 0.8215
Epoch 58/150
9/9 [==============================] - 0s 3ms/step - loss: 0.4139 - accuracy: 0.8238
Epoch 59/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4113 - accuracy: 0.8227
Epoch 60/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4119 - accuracy: 0.8215
Epoch 61/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4118 - accuracy: 0.8227
Epoch 62/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4130 - accuracy: 0.8204
Epoch 63/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4131 - accuracy: 0.8215
Epoch 64/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4130 - accuracy: 0.8193
Epoch 65/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4104 - accuracy: 0.8283
Epoch 66/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4117 - accuracy: 0.8227
Epoch 67/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4127 - accuracy: 0.8249
Epoch 68/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4115 - accuracy: 0.8227
Epoch 69/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4102 - accuracy: 0.8215
Epoch 70/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4121 - accuracy: 0.8227
Epoch 71/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4116 - accuracy: 0.8227
Epoch 72/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4089 - accuracy: 0.8260
Epoch 73/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4096 - accuracy: 0.8272
Epoch 74/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4105 - accuracy: 0.8260
Epoch 75/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4095 - accuracy: 0.8215
Epoch 76/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4078 - accuracy: 0.8316
Epoch 77/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4088 - accuracy: 0.8260
Epoch 78/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4116 - accuracy: 0.8260
Epoch 79/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4138 - accuracy: 0.8249
Epoch 80/150
9/9 [==============================] - 0s 3ms/step - loss: 0.4125 - accuracy: 0.8238
Epoch 81/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4071 - accuracy: 0.8249
Epoch 82/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4081 - accuracy: 0.8215
Epoch 83/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4065 - accuracy: 0.8305
Epoch 84/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4052 - accuracy: 0.8294
Epoch 85/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4068 - accuracy: 0.8283
Epoch 86/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4070 - accuracy: 0.8283
Epoch 87/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4069 - accuracy: 0.8238
Epoch 88/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4051 - accuracy: 0.8294
Epoch 89/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4055 - accuracy: 0.8305
Epoch 90/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4039 - accuracy: 0.8328
Epoch 91/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4073 - accuracy: 0.8272
Epoch 92/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4045 - accuracy: 0.8294
Epoch 93/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4038 - accuracy: 0.8316
Epoch 94/150
9/9 [==============================] - 0s 3ms/step - loss: 0.4046 - accuracy: 0.8260
Epoch 95/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4095 - accuracy: 0.8305
Epoch 96/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4038 - accuracy: 0.8328
Epoch 97/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4027 - accuracy: 0.8249
Epoch 98/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4062 - accuracy: 0.8294
Epoch 99/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4039 - accuracy: 0.8316
Epoch 100/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4030 - accuracy: 0.8294
Epoch 101/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4087 - accuracy: 0.8238
Epoch 102/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4020 - accuracy: 0.8283
Epoch 103/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4053 - accuracy: 0.8305
Epoch 104/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4012 - accuracy: 0.8294
Epoch 105/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4034 - accuracy: 0.8272
Epoch 106/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4011 - accuracy: 0.8272
Epoch 107/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4000 - accuracy: 0.8272
Epoch 108/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4015 - accuracy: 0.8316
Epoch 109/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4007 - accuracy: 0.8305
Epoch 110/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4041 - accuracy: 0.8294
Epoch 111/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4060 - accuracy: 0.8328
Epoch 112/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4003 - accuracy: 0.8316
Epoch 113/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4018 - accuracy: 0.8260
Epoch 114/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4031 - accuracy: 0.8260
Epoch 115/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4064 - accuracy: 0.8227
Epoch 116/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4114 - accuracy: 0.8249
Epoch 117/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4083 - accuracy: 0.8249
Epoch 118/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4018 - accuracy: 0.8339
Epoch 119/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3995 - accuracy: 0.8272
Epoch 120/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4014 - accuracy: 0.8316
Epoch 121/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3996 - accuracy: 0.8316
Epoch 122/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4007 - accuracy: 0.8249
Epoch 123/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4006 - accuracy: 0.8272
Epoch 124/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3987 - accuracy: 0.8249
Epoch 125/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4018 - accuracy: 0.8238
Epoch 126/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4011 - accuracy: 0.8283
Epoch 127/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3960 - accuracy: 0.8204
Epoch 128/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4004 - accuracy: 0.8316
Epoch 129/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3989 - accuracy: 0.8272
Epoch 130/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3998 - accuracy: 0.8316
Epoch 131/150
9/9 [==============================] - 0s 3ms/step - loss: 0.3996 - accuracy: 0.8238
Epoch 132/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3981 - accuracy: 0.8260
Epoch 133/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3995 - accuracy: 0.8249
Epoch 134/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3974 - accuracy: 0.8294
Epoch 135/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3983 - accuracy: 0.8283
Epoch 136/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3980 - accuracy: 0.8272
Epoch 137/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3966 - accuracy: 0.8260
Epoch 138/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3984 - accuracy: 0.8260
Epoch 139/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3953 - accuracy: 0.8272
Epoch 140/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3958 - accuracy: 0.8272
Epoch 141/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3957 - accuracy: 0.8272
Epoch 142/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3979 - accuracy: 0.8294
Epoch 143/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3987 - accuracy: 0.8249
Epoch 144/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3961 - accuracy: 0.8294
Epoch 145/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3962 - accuracy: 0.8272
Epoch 146/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3951 - accuracy: 0.8283
Epoch 147/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3973 - accuracy: 0.8283
Epoch 148/150
9/9 [==============================] - 0s 2ms/step - loss: 0.3938 - accuracy: 0.8316
Epoch 149/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4006 - accuracy: 0.8260
Epoch 150/150
9/9 [==============================] - 0s 2ms/step - loss: 0.4008 - accuracy: 0.8272
28/28 [==============================] - 0s 1ms/step - loss: 0.3930 - accuracy: 0.8305
0.8305274844169617